In [1]:
import torch
import numpy as np

In [2]:
from torch import nn

In [9]:
linear_layer = nn.Linear(in_features=3,out_features=1)

In [10]:
linear_layer.weight

Parameter containing:
tensor([[ 0.1806, -0.0349, -0.1638]], requires_grad=True)

In [18]:
linear_layer.bias

Parameter containing:
tensor([-0.2685], requires_grad=True)

In [11]:
linear_layer(torch.tensor([1,2,3],dtype=torch.float32))

tensor([-0.6490], grad_fn=<AddBackward0>)

In [19]:
0.1806*1 - 0.0349*2 - 0.1638*3 -0.2685

-0.6491

In [14]:
linear_layer(torch.tensor([4,5,6],dtype=torch.float32))

tensor([-0.7031], grad_fn=<AddBackward0>)

In [20]:
(0.1806*4 - 0.0349*5 - 0.1638*6) - 0.2685

-0.7034

In [24]:
torch.relu(torch.tensor(-50,dtype=torch.float32))

tensor(0.)

In [25]:
relu = nn.ReLU()

In [27]:
relu(torch.tensor(50,dtype=torch.float32))

tensor(50.)