In [2]:
#importing the libraries
import torch, numpy as np

In [ ]:
#creating numpy array
data = np.array([1,2,3,4,5])

In [ ]:
#different ways for creating tensors
output1 = torch.Tensor(data)
output2 = torch.tensor(data)
output3 = torch.from_numpy(data)
output4 = torch.as_tensor(data)
print("{}\n{}\n{}\n{}".format(output1,output2,output3,output4))

tensor([1., 2., 3., 4., 5.])
tensor([1, 2, 3, 4, 5])
tensor([1, 2, 3, 4, 5])
tensor([1, 2, 3, 4, 5])


## The difference Between the 4 ways of creating tensors mentioned above are :                                                     
1) The data type of elements in the tensor is float by default              
2) The data type of the elements in the tensor is by default the data types of the elements itself                               
3) Shares data between the numpy array and the tensor. changes in the numpy array is reflected to the tensor object and vice versa  
4) This is same as 3 but is similar to 2. because , the default data type is that of the data original data itself  

In [ ]:
#printing the datatype of all the outputs
print("{}\n{}\n{}\n{}".format(output1.dtype,output2.dtype,output3.dtype,output4.dtype))

torch.float32
torch.int64
torch.int64
torch.int64


In [ ]:
#creating an identity tensor
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [ ]:
#creating a tensor full of zeroes
torch.zeros(2,2)

tensor([[0., 0.],
        [0., 0.]])

In [ ]:
#creating a tensor full of value '1'
torch.ones(4,4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
#creating tensor with random values
torch.rand(5,3)

tensor([[0.4212, 0.1785, 0.6450],
        [0.0284, 0.9095, 0.9114],
        [0.0811, 0.5611, 0.2545],
        [0.1132, 0.3313, 0.9921],
        [0.2310, 0.4237, 0.6206]])

In [ ]:
#reshaping tensors
output5 = torch.rand(6,4)
print(output5,"\n")
print(output5.reshape(12,2),"\n")


#flattening the tensor
print(output5.flatten())

tensor([[0.2267, 0.3610, 0.3366, 0.1552],
        [0.3319, 0.3566, 0.3814, 0.9854],
        [0.4764, 0.1241, 0.8957, 0.2228],
        [0.6024, 0.0024, 0.4686, 0.9024],
        [0.0275, 0.3080, 0.7966, 0.8439],
        [0.3685, 0.7664, 0.6974, 0.0545]]) 

tensor([[0.2267, 0.3610],
        [0.3366, 0.1552],
        [0.3319, 0.3566],
        [0.3814, 0.9854],
        [0.4764, 0.1241],
        [0.8957, 0.2228],
        [0.6024, 0.0024],
        [0.4686, 0.9024],
        [0.0275, 0.3080],
        [0.7966, 0.8439],
        [0.3685, 0.7664],
        [0.6974, 0.0545]]) 

tensor([0.2267, 0.3610, 0.3366, 0.1552, 0.3319, 0.3566, 0.3814, 0.9854, 0.4764,
        0.1241, 0.8957, 0.2228, 0.6024, 0.0024, 0.4686, 0.9024, 0.0275, 0.3080,
        0.7966, 0.8439, 0.3685, 0.7664, 0.6974, 0.0545])


In [ ]:
#squeeze and unsqueeze tensor operations
output6 = torch.as_tensor([[1,2,3,4,5,6,6,7]])
print("{}\n{}\n{}".format(output6,output6.squeeze(),output6.squeeze().unsqueeze(dim=0)))

tensor([[1, 2, 3, 4, 5, 6, 6, 7]])
tensor([1, 2, 3, 4, 5, 6, 6, 7])
tensor([[1, 2, 3, 4, 5, 6, 6, 7]])


In [ ]:
#tensor concatenation
tensor1 = torch.tensor([[1,2,3,4,5]])
tensor2 = torch.tensor([[6,7,8,9,10]])
print("{}\n{}".format(torch.cat((tensor1,tensor2),axis=1),torch.cat((tensor1,tensor2),axis=0)))

tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])
tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])


In [6]:
data = np.array([0,1,2,3,4,5])
tensor = torch.tensor(data)
print(tensor)

tensor([0, 1, 2, 3, 4, 5])
